import fs from 'fs/promises';
import path from 'path';

async function generateConsts() {
    const url = process.env.OMU_ORIGIN || process.env.CF_PAGES_URL;
    const isBeta = process.env.IS_BETA || 'false';
    const constsFile = path.join('src', 'lib', 'consts.ts');
    await fs.writeFile(constsFile, `// DO NOT EDIT. This file is automatically generated by build-pre.ts
export const CF_PAGES_URL = '${url}';
export const IS_BETA = ${isBeta === 'true'};
`);
}

await generateConsts();
