[package]
name = "omuchat"
version = "0.1.0"
description = "A OMUCHAT client built with Tauri."
authors = ["2ji_han"]
license = ""
repository = ""
default-run = "omuchat"
edition = "2021"
rust-version = "1.60"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[build-dependencies]
tauri-build = { version = "1.4.0", features = [] }

[dependencies]
serde_json = "1.0"
serde = { version = "1.0", features = ["derive"] }
tauri = { version = "1.4.0", features = [ "fs-read-file", "window-close", "dialog-all", "shell-open", "window-unminimize", "window-unmaximize", "window-start-dragging", "window-hide", "window-minimize", "window-show", "window-set-focus", "window-maximize", "window-create", "updater", "system-tray"] }
window-shadows = "0.2.1"
portpicker = "0.1" # used in the example to pick a random free port
local-ip-address = "0.6.1"
directories = "5.0.1"
once_cell = "1.16.0"
reqwest = { version = "0.11", features = ["json"] }
tokio = { version = "1.34.0", features = ["full"] }
async_zip = { version = "0.0.11", features = ["full"] }
tokio-tar = "0.3.0"
async-compression = { version= "0.3.15", features = ["gzip", "brotli", "zstd"] }
tracing = "0.1"
tracing-subscriber = { version = "0.3", features = ["fmt", "env-filter"] }
tracing-appender = "0.2"
rand = "0.8"
log = "0.4"
thiserror = "1"
tiny_http = "0.12"
http = "1.1.0"
zip = "0.6.6"
anyhow = "1.0.79"

[features]
# this feature is used for production builds or when `devPath` points to the filesystem and the built-in dev server is disabled.
# If you use cargo directly instead of tauri's cli you can use this feature flag to switch between tauri's `dev` and `build` modes.
# DO NOT REMOVE!!
custom-protocol = [ "tauri/custom-protocol" ]
